/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Presentadores.PresentadorVistaPrincipal;

import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
/**
 *
 * @author laboratorio
 */
public class VistaPrincipal extends javax.swing.JFrame {

    private PresentadorVistaPrincipal presentadorVistaPrincipal;
    
    DefaultTableModel movimientosTableModel;
    String movimientosMatrix[][] = {};
    String movimientosHead[] = {"Concepto", "Débito", "Crédito", "Saldo"};
    
    public VistaPrincipal() {
        initComponents();
        
        this.presentadorVistaPrincipal = new PresentadorVistaPrincipal(this);
    }
    
    
    public javax.swing.JTextField getNombreTextField(){
        return this.nombreTextField;
    }
    
    public javax.swing.JTextField getApellidoTextField(){
        return this.apellidoTextField;
    }
    
    public javax.swing.JTextField getCuit1TextField(){
        return this.cuit1TextField;
    }
    
    public javax.swing.JTextField getCuit2TextField(){
        return this.cuit2TextField;
    }
    
    public javax.swing.JTextField getCuit3TextField(){
        return this.cuit3TextField;
    }
    
    public javax.swing.JTextField getSaldoInicialTextField(){
        return this.saldoInicialTextField;
    }
    
    public javax.swing.JComboBox<String> getCuitOrigenComboBox(){
        return this.cuitOrigenComboBox;
    }
    
    public javax.swing.JComboBox<String> getCuitDestinoComboBox(){
        return this.cuitDestinoComboBox;
    }
    
    public javax.swing.JTextField getMontoTextField(){
        return this.montoTextField;
    }
    
    public javax.swing.JComboBox<String> getCuitMovimientosComboBox(){
        return this.cuitMovimientosComboBox;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vistaPrincipalTabbedPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        nombreLabel = new javax.swing.JLabel();
        apellidoLabel = new javax.swing.JLabel();
        cuitLabel = new javax.swing.JLabel();
        saldoInicialLabel = new javax.swing.JLabel();
        saldoInicialTextField = new javax.swing.JTextField();
        cuit1TextField = new javax.swing.JTextField();
        apellidoTextField = new javax.swing.JTextField();
        nombreTextField = new javax.swing.JTextField();
        guardarDatosCuentaButton = new javax.swing.JButton();
        cuit2TextField = new javax.swing.JTextField();
        cuit3TextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cuitOrigenLabel = new javax.swing.JLabel();
        cuitDestionoLabel = new javax.swing.JLabel();
        cuitOrigenComboBox = new javax.swing.JComboBox<>();
        cuitDestinoComboBox = new javax.swing.JComboBox<>();
        montoLabel = new javax.swing.JLabel();
        montoTextField = new javax.swing.JTextField();
        guardarTranferenciaButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        cuitMovimientosLabel = new javax.swing.JLabel();
        cuitMovimientosComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        movimientosTable = new javax.swing.JTable();
        mostrarMovimientosButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombreLabel.setText("Nombre:");

        apellidoLabel.setText("Apellido:");

        cuitLabel.setText("CUIT:");

        saldoInicialLabel.setText("Saldo inicial:");

        cuit1TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cuit1TextFieldKeyTyped(evt);
            }
        });

        guardarDatosCuentaButton.setText("Guardar datos de cuenta");
        guardarDatosCuentaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarDatosCuentaButtonActionPerformed(evt);
            }
        });

        cuit2TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cuit2TextFieldKeyTyped(evt);
            }
        });

        cuit3TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cuit3TextFieldKeyTyped(evt);
            }
        });

        jLabel2.setText("-");

        jLabel3.setText("-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(guardarDatosCuentaButton)
                .addGap(109, 109, 109))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saldoInicialLabel)
                    .addComponent(cuitLabel)
                    .addComponent(apellidoLabel)
                    .addComponent(nombreLabel))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(apellidoTextField)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cuit3TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cuit1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(jLabel2)
                                .addGap(10, 10, 10)
                                .addComponent(cuit2TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addGap(42, 42, 42))
                            .addComponent(nombreTextField)
                            .addComponent(saldoInicialTextField))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidoLabel)
                    .addComponent(apellidoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuitLabel)
                    .addComponent(cuit1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuit2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuit3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saldoInicialLabel)
                    .addComponent(saldoInicialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(guardarDatosCuentaButton)
                .addGap(41, 41, 41))
        );

        vistaPrincipalTabbedPane.addTab("Datos Cuenta", jPanel2);

        cuitOrigenLabel.setText("CUIT origen:");

        cuitDestionoLabel.setText("CUIT destino:");

        montoLabel.setText("Monto:");

        guardarTranferenciaButton.setText("Guardar transferencia");
        guardarTranferenciaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarTranferenciaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cuitOrigenLabel)
                    .addComponent(cuitDestionoLabel)
                    .addComponent(montoLabel))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cuitOrigenComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cuitDestinoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(montoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addComponent(guardarTranferenciaButton)
                .addGap(119, 119, 119))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuitOrigenLabel)
                    .addComponent(cuitOrigenComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuitDestionoLabel)
                    .addComponent(cuitDestinoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(montoLabel)
                    .addComponent(montoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(guardarTranferenciaButton)
                .addGap(49, 49, 49))
        );

        vistaPrincipalTabbedPane.addTab("Transferencias", jPanel1);

        cuitMovimientosLabel.setText("CUIT:");

        movimientosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(movimientosTable);

        mostrarMovimientosButton.setText("Mostrar movimientos");
        mostrarMovimientosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarMovimientosButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(mostrarMovimientosButton)
                        .addGap(134, 134, 134))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(cuitMovimientosLabel)
                                .addGap(18, 18, 18)
                                .addComponent(cuitMovimientosComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(22, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuitMovimientosLabel)
                    .addComponent(cuitMovimientosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(mostrarMovimientosButton)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        vistaPrincipalTabbedPane.addTab("Movimientos", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vistaPrincipalTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vistaPrincipalTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarDatosCuentaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarDatosCuentaButtonActionPerformed
        this.presentadorVistaPrincipal.guardarDatosCuenta();
        if (presentadorVistaPrincipal.getCuitGuardado() != null){
            cuitOrigenComboBox.addItem(presentadorVistaPrincipal.getCuitGuardado());
            cuitDestinoComboBox.addItem(presentadorVistaPrincipal.getCuitGuardado());
            cuitMovimientosComboBox.addItem(presentadorVistaPrincipal.getCuitGuardado());
        }
                
    }//GEN-LAST:event_guardarDatosCuentaButtonActionPerformed

    private void guardarTranferenciaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarTranferenciaButtonActionPerformed
        this.presentadorVistaPrincipal.guardarTransferencia();
    }//GEN-LAST:event_guardarTranferenciaButtonActionPerformed

    private void cuit1TextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cuit1TextFieldKeyTyped
        if (cuit1TextField.getText().length() == 2){
            evt.consume();
        }
    }//GEN-LAST:event_cuit1TextFieldKeyTyped

    private void cuit2TextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cuit2TextFieldKeyTyped
        if (cuit2TextField.getText().length() == 8){
            evt.consume();
        }
    }//GEN-LAST:event_cuit2TextFieldKeyTyped

    private void cuit3TextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cuit3TextFieldKeyTyped
        if (cuit3TextField.getText().length() == 1){
            evt.consume();
        }
    }//GEN-LAST:event_cuit3TextFieldKeyTyped

    private void mostrarMovimientosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarMovimientosButtonActionPerformed
        ArrayList<String[]> movimientosToString = presentadorVistaPrincipal.mostrarMovimientos();
        
        this.movimientosTableModel = new DefaultTableModel(movimientosMatrix, movimientosHead);
        
        for (String[] movimientos : movimientosToString){
            movimientosTableModel.addRow(movimientos);
        }
        movimientosTable.setModel(movimientosTableModel);
    }//GEN-LAST:event_mostrarMovimientosButtonActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidoLabel;
    private javax.swing.JTextField apellidoTextField;
    private javax.swing.JTextField cuit1TextField;
    private javax.swing.JTextField cuit2TextField;
    private javax.swing.JTextField cuit3TextField;
    private javax.swing.JComboBox<String> cuitDestinoComboBox;
    private javax.swing.JLabel cuitDestionoLabel;
    private javax.swing.JLabel cuitLabel;
    private javax.swing.JComboBox<String> cuitMovimientosComboBox;
    private javax.swing.JLabel cuitMovimientosLabel;
    private javax.swing.JComboBox<String> cuitOrigenComboBox;
    private javax.swing.JLabel cuitOrigenLabel;
    private javax.swing.JButton guardarDatosCuentaButton;
    private javax.swing.JButton guardarTranferenciaButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel montoLabel;
    private javax.swing.JTextField montoTextField;
    private javax.swing.JButton mostrarMovimientosButton;
    private javax.swing.JTable movimientosTable;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JLabel saldoInicialLabel;
    private javax.swing.JTextField saldoInicialTextField;
    private javax.swing.JTabbedPane vistaPrincipalTabbedPane;
    // End of variables declaration//GEN-END:variables
}
